### PR TITLE
change the mashape logo to kong 

### PR DESCRIPTION
**Pull request by judithpatudith**
Mashape is now Kong, and the log has changed. This PR updates the logo on the sponsor's page and changes the name and URL. 

I wasn't successful at building my changes locally. Any advice is welcome!

### CODE REVIEW

**Comment by judithpatudith** [comment]
@thibaultcha if you have some time I'd love a review or help with testing 🙂

**Comment by agentzh** [comment]
Never mind. I merged it myself.

**Comment by agentzh** [comment]
Alas. The kong logo is just too big...

**Comment by agentzh** [comment]
screen shot 2019-01-30 at 11 36 35 pm

**Comment by agentzh** [comment]
@judithpatudith Please create another PR to fix this.

**Comment by judithpatudith** [comment]
New PR [here](https://github.com/openresty/openresty.org/pull/82). Thanks @agentzh

**Pull request closed without merging**
